### ISSUE TITLE
No water in the matrix 

### ISSUE THREAD

**Issue by nmh4598** [cordmaur/WaterDetect#17]
Here, I use Waterdetect to extract water bodies from a scene of Sentinel 2 imagery.

# Code

```
import waterdetect as wd
import rasterio
```
```
config = wd.DWConfig(config_file='WaterDetect.ini')
config.clustering_bands, config.detect_water_cluster
```

>Loading configuration file WaterDetect.ini
File WaterDetect.ini verified.
([['mndwi', 'ndwi', 'Mir2']], 'maxmbwi')

```
b3 = rasterio.open('.../T31UES_20220719T105041_B03_20m.jp2').read()
b4 = rasterio.open('.../T31UES_20220719T105041_B04_20m.jp2').read()
nir = rasterio.open('.../T31UES_20220719T105041_B8A_20m.jp2').read()
mir1 = rasterio.open('.../T31UES_20220719T105041_B11_20m.jp2').read()
mir2 = rasterio.open('.../T31UES_20220719T105041_B12_20m.jp2').read()
bands = {'Green': b3.squeeze()/10000, 'Red': b4.squeeze()/10000, 'Nir': nir.squeeze()/10000,'Mir': mir1.squeeze()/10000,'Mir2': mir2.squeeze()/10000}
wmask = wd.DWImageClustering(bands=bands, bands_keys=['Mir2', 'mndwi', 'ndwi'], invalid_mask=None, config=config)
mask = wmask.run_detect_water()
plt.imshow(wmask.cluster_matrix)

```

> Selection of best number of clusters using Calinski-Harabasz Index:
k=2 :Calinski_harabaz index=150.58256179023687
k=3 :Calinski_harabaz index=81.65946151674528
k=4 :Calinski_harabaz index=1867.2173765910154
k=5 :Calinski_harabaz index=3691.9700226205587
k=6 :Calinski_harabaz index=3017.54521958539
k=7 :Calinski_harabaz index=2515.1876336606165
Applying clusters based naive bayes classifier
Assgnin 1 to cluster_id 3
Skipping cluster_id 3
<matplotlib.image.AxesImage at 0x7fa03fea6430>
<div>      
<img  style="width:550px;" src="https://raw.githubusercontent.com/nmh4598/Python-Master/main/S2/41.png">
</div>  

`plt.imshow(wmask.water_mask==1)`

<div>      
<img  style="width:550px;" src="https://raw.githubusercontent.com/nmh4598/Python-Master/main/S2/42.png">
</div> 

`np.unique(wmask.water_mask)`
> array([0], dtype=int8)

`np.unique(wmask.cluster_matrix)`
> array([0, 2, 3, 4, 5], dtype=int8)

# Questions
Why my matrix "wmask.water_mask" and "wmask.water_mask" have no cluster "1" which is water ?

**Comment by cordmaur** [comment]
Hi @nmh4598,

I have tested exactly the same Tile (T31UES_20220720T021032)
It worked normally. Check the code/output:
![image](https://user-images.githubusercontent.com/19617404/185434843-9d550f3a-8f02-4b96-a5ff-cfd45585c66a.png)

Two minor differences:
1- I changed the reference_band in WaterDetect.ini to Green (to avoid the necessity to pass Red). But it should not affect anything in the output.
2- I obtain the L2A images directly from a data provider, instead of downloading it. That should not be an issue either. 

I suggest you to re-check the version (1.5.12) and retry.
If it doesn't work, you can share with me (dropbox or other) the original image you downloaded, so I can replicate.

Regards,
Mauricio

**Comment by cordmaur** [comment]
Closed due to inactivity.
