### ISSUE TITLE
Effect of changing the reference band

### ISSUE THREAD

**Issue by haozhen315** [cordmaur/WaterDetect#20]
Hi Cordmaur,

Thanks for sharing this outstanding work. 

I am working on a project related to water body identification and would like to have data with as high resolution as possible. I have found that by modifying the reference_band = Mir to Nir or other 10m band in the ".init" file, then I can change the resolution (to 10m) and I have successfully obtained the results. 

I would like to ask if the output of the model at 10m resolution (reference_band = Nir) is better than the 10m image obtained by simply interpolating the 20m result (reference_band = Mir) with NDWI+B12 as input. I am asking this question only because I am not sure why you defaulted the reference band in the code to MIR instead of the higher resolution NIR (or other 10m bands), since your article clearly states a 10m result.

Best,
Zhen Hao

**Comment by haozhen315** [comment]
Just to add: the product used is Sentinel 2 - L2A from Sen2Cor

**Comment by cordmaur** [comment]
Hi haozhen,

I'm glad to know the package is being useful. 
Concerning default "reference band" it has been changed to 20m (mir) just for memory consumption reasons and overall performance. Some people were not able to run it on 16gb pc.
If you need 10m output, just leave it as Nir as you did.

For the clustering combination, we tested various configurations that are presented in the peer reviewed article. The option for a SWIR (Mir and Mir2) band in the clustering is because Nir is very sensitive to turbidity waters... so that will depend on your area of study. If you have more clear waters, you can try a pure 10m processing with NDWI and B8 in the clustering. 

Hope it helps.
Mauricio 


Enviado do meu iPad

**Comment by haozhen315** [comment]
Hi Cordmaur,

Thank you very much for the reply. Yes it really helps.

Best,
Zhen Hao
